# Travis CI Configuration
# https://docs.travis-ci.com
language: c

git:
  depth: 3

sudo: false
dist: trusty

install:
  pip install --user pre-commit

script:
  - git diff-tree -z --no-commit-id --name-only -r HEAD | xargs --null pre-commit run --files

cache:
  pip: true
