name: application
version: 1
summary: Qt Application Example
description: A simple text editor
confinement: devmode

apps:
  application:
    command: desktop-launch application
    plugs: [unity7, home]

parts:
  application:
    source: src/
    plugin: qmake
    qt-version: qt5
    after: [qt5]
  qt5:
    source: .
    plugin: make
    make-parameters: ["SRC_DIR=../src"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - appmenu-qt5

#plugs:
#  platform:
#      content: ubuntu-app-platform1
#      default-provider: ubuntu-app-platform
#      interface: content
#      target: ubuntu-app-platform
